"""The book formats this library writes by hand.

Books are the one library where the *files* are not media, so ffmpeg cannot
make them. Everything here is written directly out of the standard library —
the same line `vobsub.py` takes, and for the same reason: a QA tool that pulls
in an EPUB library, a PDF library and a comic library to produce four fixture
files has traded a dependency it must trust for code it could have read.

None of these are rich documents. An EPUB with one chapter, a PDF with a few
pages of Helvetica and a zip of JPEGs are enough, because what is under test is
the *resolve* — which extension Jellyfin accepts, which metadata dialect it
reads out of which place, and which image it picks for the cover. A better
novel would not test any of it harder.
"""

from __future__ import annotations

import json
import os
import zipfile

# Every archive member is stamped with this instead of the clock. A zip stores
# a modification time per entry and a tar stores one per member, so a builder
# that lets either default writes a file that differs between two builds of
# the same library — silently, because nothing about the content changed.
# 1980-01-01 is the zip epoch and the earliest a zip can express, which is
# also what `ZipInfo(name)` uses when it is constructed without a date.
ARCHIVE_EPOCH = (1980, 1, 1, 0, 0, 0)


def _member(name: str, compress=zipfile.ZIP_DEFLATED) -> zipfile.ZipInfo:
    info = zipfile.ZipInfo(name, date_time=ARCHIVE_EPOCH)
    info.compress_type = compress
    # Without this the entry has mode 0, and some tools unpack it unreadable.
    info.external_attr = 0o644 << 16
    return info

# --------------------------------------------------------------------------
# EPUB
# --------------------------------------------------------------------------


def write_epub(path: str, title: str, author: str) -> None:
    """A minimal EPUB 3: mimetype, container, one OPF, one chapter."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with zipfile.ZipFile(path, "w") as zf:
        # mimetype must be first and stored uncompressed — that is what makes
        # the file identifiable as an EPUB by its first bytes.
        zf.writestr(_member("mimetype", zipfile.ZIP_STORED),
                    "application/epub+zip")
        zf.writestr(_member("META-INF/container.xml"),
                    '<?xml version="1.0"?>\n'
                    '<container version="1.0" '
                    'xmlns="urn:oasis:names:tc:opendocument:xmlns:container">\n'
                    '  <rootfiles><rootfile full-path="OEBPS/content.opf" '
                    'media-type="application/oebps-package+xml"/></rootfiles>\n'
                    '</container>\n')
        zf.writestr(_member("OEBPS/content.opf"),
                    f'<?xml version="1.0" encoding="utf-8"?>\n'
                    f'<package xmlns="http://www.idpf.org/2007/opf" version="3.0" '
                    f'unique-identifier="bookid">\n'
                    f'  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">\n'
                    f'    <dc:identifier id="bookid">stdjflib-{title}</dc:identifier>\n'
                    f'    <dc:title>{title}</dc:title>\n'
                    f'    <dc:creator>{author}</dc:creator>\n'
                    f'    <dc:language>en</dc:language>\n'
                    f'  </metadata>\n'
                    f'  <manifest><item id="c1" href="ch1.xhtml" '
                    f'media-type="application/xhtml+xml"/></manifest>\n'
                    f'  <spine><itemref idref="c1"/></spine>\n'
                    f'</package>\n')
        zf.writestr(_member("OEBPS/ch1.xhtml"),
                    f'<?xml version="1.0" encoding="utf-8"?>\n'
                    f'<html xmlns="http://www.w3.org/1999/xhtml"><head>'
                    f'<title>{title}</title></head><body>\n'
                    f'<h1>{title}</h1><p>By {author}.</p>\n'
                    f'<p>Generated by stdjflib as library test content.</p>\n'
                    f'</body></html>\n')


# --------------------------------------------------------------------------
# PDF
# --------------------------------------------------------------------------
#
# Written by hand rather than with a library, and it is a smaller job than it
# sounds: a PDF is a list of numbered objects, a cross-reference table of their
# byte offsets, and a trailer naming the catalogue. The only part that has to
# be exactly right is the xref — every entry is a ten-digit offset in a
# twenty-byte record, and a reader that cannot parse it falls back to scanning
# the file and finds the pages anyway, which is how a broken one still opens.
# So the offsets are measured from the bytes actually emitted, never computed
# ahead of them.
#
# The page count is the whole point of the fixture: Jellyfin stores it as
# `RunTimeTicks`, so it is the one number a client can read back off a book.


def _pdf_escape(text: str) -> str:
    """Escape for a PDF literal string. Backslash first or it doubles."""
    return text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")


def _pdf_ascii(text: str) -> bytes:
    """PDF literal strings here are WinAnsi; anything else becomes '?'.

    The fixture titles are Latin on purpose, so this only ever bites if
    someone gives a PDF a Japanese name — at which point a replaced character
    in a page of body text is a better outcome than a build that fails.
    """
    return _pdf_escape(text).encode("ascii", "replace")


def pdf_bytes(title: str, author: str, pages: int) -> bytes:
    """A valid multi-page PDF, with `pages` pages of readable text."""
    if pages < 1:
        raise ValueError("a PDF needs at least one page")
    bodies: list[bytes] = []

    def add(body: bytes) -> int:
        bodies.append(body)
        return len(bodies)

    catalog = add(b"")        # 1 — patched below, once the pages exist
    pages_node = add(b"")     # 2 — likewise; every page names it as /Parent
    font = add(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica "
               b"/Encoding /WinAnsiEncoding >>")

    kids = []
    for n in range(1, pages + 1):
        lines = [title, f"By {author}.", f"Page {n} of {pages}.",
                 "Generated by stdjflib as library test content."]
        data = (b"BT /F1 22 Tf 72 700 Td 32 TL\n"
                + b"".join(b"(%s) Tj T*\n" % _pdf_ascii(line)
                           for line in lines)
                + b"ET\n")
        content = add(b"<< /Length %d >>\nstream\n" % len(data)
                      + data + b"endstream")
        kids.append(add(
            b"<< /Type /Page /Parent %d 0 R /MediaBox [0 0 612 792] "
            b"/Resources << /Font << /F1 %d 0 R >> >> /Contents %d 0 R >>"
            % (pages_node, font, content)))

    bodies[catalog - 1] = b"<< /Type /Catalog /Pages %d 0 R >>" % pages_node
    bodies[pages_node - 1] = (
        b"<< /Type /Pages /Count %d /Kids [%s] >>"
        % (pages, b" ".join(b"%d 0 R" % k for k in kids)))

    # The binary comment on line two is what tells a transfer agent this is not
    # a text file. Dropping it is legal and gets the file mangled by anything
    # that thinks it may translate line endings.
    out = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = []
    for number, body in enumerate(bodies, 1):
        offsets.append(len(out))
        out += b"%d 0 obj\n" % number + body + b"\nendobj\n"

    xref = len(out)
    out += b"xref\n0 %d\n" % (len(bodies) + 1)
    # Object zero is always the head of the free list, and the records are
    # fixed-width: exactly twenty bytes each, trailing space included.
    out += b"0000000000 65535 f \n"
    for offset in offsets:
        out += b"%010d 00000 n \n" % offset
    out += (b"trailer\n<< /Size %d /Root %d 0 R /Info << /Title (%s) "
            b"/Author (%s) >> >>\n"
            % (len(bodies) + 1, catalog, _pdf_ascii(title), _pdf_ascii(author)))
    out += b"startxref\n%d\n%%%%EOF\n" % xref
    return bytes(out)


def write_pdf(path: str, title: str, author: str, pages: int) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as fh:
        fh.write(pdf_bytes(title, author, pages))


def pdf_page_count(path: str) -> int | None:
    """Count a PDF's pages by reading the file, for `verify`.

    Deliberately a second statement of the format rather than a call back into
    the writer — a check that inherits its expectations from the thing it is
    checking is not a check, which is the same reason `verify._ARTWORK_STEMS`
    spells the artwork mapping out again. This counts page *objects*, where
    the writer declares a `/Count`, so the two disagree if either is wrong.
    """
    try:
        with open(path, "rb") as fh:
            blob = fh.read()
    except OSError:
        return None
    if not blob.startswith(b"%PDF-"):
        return None
    # `/Type /Pages` is the tree node and `/Type /Page` a leaf; matching the
    # shorter one first would count the node as a page. Both spellings of the
    # separator occur in the wild.
    count = 0
    for token in (b"/Type/Page", b"/Type /Page"):
        start = 0
        while True:
            at = blob.find(token, start)
            if at < 0:
                break
            start = at + len(token)
            tail = blob[start:start + 1]
            # A leaf ends here; `/Pages` continues with an "s".
            if tail in (b"", b" ", b"/", b">", b"\r", b"\n", b"\t"):
                count += 1
    return count


# --------------------------------------------------------------------------
# Comic archives
# --------------------------------------------------------------------------


def write_cbz(path: str, pages: list[tuple[str, str]], *,
              comment: bytes | None = None,
              extra: dict[str, str] | None = None) -> None:
    """A comic archive: a zip of images, which is all a CBZ is.

    `pages` is (name-in-archive, path-on-disk); `extra` adds text members such
    as an internal `ComicInfo.xml`; `comment` is the zip's *archive* comment,
    which is where the ComicBookInfo dialect lives.

    Stored rather than deflated, matching what comic archives are in the wild —
    the pages are JPEG and already compressed, so deflating them buys nothing
    and costs a scan every time something opens the file.
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with zipfile.ZipFile(path, "w", zipfile.ZIP_STORED) as zf:
        for name, source in pages:
            # Not `zf.write(source, name)`: that takes the entry's timestamp
            # from the file on disk, so the archive would differ between two
            # builds of an identical library.
            with open(source, "rb") as fh:
                zf.writestr(_member(name, zipfile.ZIP_STORED), fh.read())
        for name, text in (extra or {}).items():
            zf.writestr(_member(name, zipfile.ZIP_STORED), text)
        if comment is not None:
            zf.comment = comment


def write_cbt(path: str, pages: list[tuple[str, str]], *,
              extra: dict[str, str] | None = None) -> None:
    """A comic archive as a tar, which is what `.cbt` is.

    Jellyfin reads `.cb7`, `.cbr`, `.cbt` and `.cbz` through SharpCompress, so
    a tar gets a cover and a page count exactly as a zip does — but the two
    metadata providers that read *inside* an archive are hard-restricted to
    `.cbz`, so the `ComicInfo.xml` this puts in is deliberately never read.
    That is the fixture: the same bytes in a `.cbz` are metadata and here are
    a page.

    `.cbt` rather than `.cbr` because a RAR cannot be written from the
    standard library and this can. It answers the same question.
    """
    import io
    import tarfile

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with tarfile.open(path, "w") as tf:
        for name, source in pages:
            info = tarfile.TarInfo(name)
            info.size = os.path.getsize(source)
            # Not the file's mtime: a tar records it, so the archive would
            # differ between two builds of the same library.
            info.mtime = 0
            info.mode = 0o644
            info.uid = info.gid = 0
            info.uname = info.gname = ""
            with open(source, "rb") as fh:
                tf.addfile(info, fh)
        for name, text in (extra or {}).items():
            data = text.encode("utf-8")
            info = tarfile.TarInfo(name)
            info.size = len(data)
            info.mtime = 0
            info.mode = 0o644
            info.uid = info.gid = 0
            info.uname = info.gname = ""
            tf.addfile(info, io.BytesIO(data))


def comicinfo_xml(*, title: str, series: str, number: int, year: int,
                  summary: str, publisher: str, genres: list[str],
                  writer: str, penciller: str = "", colourist: str = "",
                  language: str = "en") -> str:
    """The ComicRack `ComicInfo.xml` dialect, as `ComicInfoReader` reads it.

    Only the elements the server has an XPath for are written. It reads
    Title, Series, Number, Summary, Year/Month/Day, Genre (comma split),
    Publisher, LanguageISO and Manga, plus the people — and `Colourist` is
    spelled the British way in the server, which is the kind of detail a
    fixture exists to pin.
    """
    def esc(text: str) -> str:
        return (str(text).replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;"))

    rows = [
        ("Title", title), ("Series", series), ("Number", number),
        ("Summary", summary), ("Year", year), ("Month", 1), ("Day", 1),
        ("Genre", ", ".join(genres)), ("Publisher", publisher),
        ("Writer", writer), ("Penciller", penciller),
        ("Colourist", colourist), ("LanguageISO", language),
    ]
    body = "".join(f"  <{tag}>{esc(value)}</{tag}>\n"
                   for tag, value in rows if value != "")
    return ('<?xml version="1.0" encoding="utf-8"?>\n'
            '<ComicInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
            'xmlns:xsd="http://www.w3.org/2001/XMLSchema">\n'
            f'{body}</ComicInfo>\n')


def comicbookinfo_json(*, title: str, series: str, issue: int, year: int,
                       month: int, publisher: str, genre: str, comments: str,
                       credits: list[tuple[str, str]], tags: list[str],
                       language: str = "en") -> bytes:
    """The ComicBookInfo dialect, which lives in the zip's *archive comment*.

    A zip comment is a free-text trailer nothing else looks at, which is why
    this convention could be bolted onto an existing format at all — and why
    it is invisible to anything that only lists entries. The server reads it
    with `JsonSerializer` into `ComicBookInfoFormat`, so the container key has
    to be spelled exactly `ComicBookInfo/1.0`.

    `credits` is (person, role); the role is parsed with
    `Enum.TryParse<PersonKind>`, so an unrecognised one silently becomes
    `Unknown` rather than failing.
    """
    payload = {
        "appID": "stdjflib/1.0",
        # Not "now": a wall-clock stamp here would make two builds of the same
        # library differ, which is the one thing this tool must never do.
        "lastModified": "2020-01-01 00:00:00 +0000",
        "ComicBookInfo/1.0": {
            "series": series,
            "title": title,
            "issue": issue,
            "publisher": publisher,
            "publicationMonth": month,
            "publicationYear": year,
            "genre": genre,
            "language": language,
            "comments": comments,
            "credits": [{"person": person, "role": role}
                        for person, role in credits],
            "tags": tags,
        },
    }
    return json.dumps(payload, ensure_ascii=False,
                      separators=(",", ":")).encode("utf-8")


# --------------------------------------------------------------------------
# The formats that resolve and cannot be opened
# --------------------------------------------------------------------------

def palmdb_bytes(title: str, creator: str) -> bytes:
    """A PalmDB header, which is what a `.mobi` and an `.azw3` both are.

    Deliberately a header and nothing else: the point of these fixtures is
    that Jellyfin *catalogues* them — `BookResolver` accepts the extension and
    hands back an ordinary Book with metadata and artwork — while no client
    can open one. Nothing in the server parses a byte of the content, so a
    real book inside would test nothing that this does not.

    It is a genuine PalmDB header rather than arbitrary bytes so that the file
    is at least structurally what its extension claims. Anything that tries to
    read further will find no records and should say so, which is the honest
    outcome for a file that exists to have no reader.
    """
    name = title.encode("ascii", "replace")[:31].ljust(32, b"\x00")
    header = bytearray(name)
    header += (0).to_bytes(2, "big")     # attributes
    header += (0).to_bytes(2, "big")     # version
    # PalmDB times are seconds since 1904. Fixed, not "now" — see EPOCH.
    stamp = (2020 - 1904) * 365 * 24 * 3600
    header += stamp.to_bytes(4, "big")   # creation date
    header += stamp.to_bytes(4, "big")   # modification date
    header += (0).to_bytes(4, "big")     # last backup
    header += (0).to_bytes(4, "big")     # modification number
    header += (0).to_bytes(4, "big")     # app info id
    header += (0).to_bytes(4, "big")     # sort info id
    header += b"BOOK"                    # type
    header += b"MOBI"                    # creator
    header += (0).to_bytes(4, "big")     # unique id seed
    header += (0).to_bytes(4, "big")     # next record list id
    header += (0).to_bytes(2, "big")     # number of records
    trailer = (f"stdjflib placeholder. {title}, by {creator}. "
               f"This file has a valid PalmDB header and no book inside: "
               f"Jellyfin catalogues it and no client can open it, which is "
               f"the case it exists to cover.\n").encode("utf-8")
    return bytes(header) + trailer


def write_palmdb(path: str, title: str, creator: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as fh:
        fh.write(palmdb_bytes(title, creator))


# --------------------------------------------------------------------------
# Reading back, for `verify`
# --------------------------------------------------------------------------

# What `ComicImageProvider` will open, and what it will accept as a page.
ARCHIVE_EXTENSIONS = (".cb7", ".cbr", ".cbt", ".cbz")
COVER_EXTENSIONS = (".png", ".jpeg", ".jpg", ".webp", ".bmp", ".gif")


def archive_entries(path: str) -> list[str] | None:
    """Every non-directory entry in a comic archive, or None if unreadable.

    The count matters because it *is* the page count: `ProbeProvider` stores
    `archive.Entries.Count(e => !e.IsDirectory) * 10000` as `RunTimeTicks`,
    counting a `ComicInfo.xml` as cheerfully as a page.
    """
    import tarfile

    try:
        if path.lower().endswith(".cbz"):
            with zipfile.ZipFile(path) as zf:
                return [i.filename for i in zf.infolist() if not i.is_dir()]
        if path.lower().endswith(".cbt"):
            with tarfile.open(path) as tf:
                return [m.name for m in tf.getmembers() if not m.isdir()]
    except (OSError, zipfile.BadZipFile, tarfile.TarError):
        return None
    return None


def archive_cover(names: list[str]) -> str | None:
    """Which entry Jellyfin would use as the cover.

    `ComicImageProvider.FindCoverEntryInArchiveAsync`, restated rather than
    called: an entry named exactly `cover.<ext>` — tried in the order below,
    which puts `.png` ahead of `.jpg` — and otherwise the alphabetically first
    entry by full key that has an image extension. Both halves matter: the
    exact match takes no path prefix and is case-sensitive, so `Cover.jpg` and
    `images/cover.jpg` both fall through to the sort.
    """
    for ext in COVER_EXTENSIONS:
        if "cover" + ext in names:
            return "cover" + ext
    for name in sorted(names):
        if os.path.splitext(name)[1].lower() in COVER_EXTENSIONS:
            return name
    return None
