"""The book formats this library writes by hand.

Books are the one library where the *files* are not media, so ffmpeg cannot
make them. Everything here is written directly out of the standard library —
the same line `vobsub.py` takes, and for the same reason: a QA tool that pulls
in an EPUB library, a PDF library and a comic library to produce four fixture
files has traded a dependency it must trust for code it could have read.

None of these are rich documents. An EPUB with one chapter, a PDF with a few
pages of Helvetica and a zip of JPEGs are enough, because what is under test is
the *resolve* — which extension Jellyfin accepts, which metadata dialect it
reads out of which place, and which image it picks for the cover. A better
novel would not test any of it harder.
"""

from __future__ import annotations

import hashlib
import json
import os
import zipfile

from . import config

# Every archive member is stamped with this instead of the clock. A zip stores
# a modification time per entry and a tar stores one per member, so a builder
# that lets either default writes a file that differs between two builds of
# the same library — silently, because nothing about the content changed.
# 1980-01-01 is the zip epoch and the earliest a zip can express, which is
# also what `ZipInfo(name)` uses when it is constructed without a date.
ARCHIVE_EPOCH = (1980, 1, 1, 0, 0, 0)


def _member(name: str, compress=zipfile.ZIP_DEFLATED) -> zipfile.ZipInfo:
    info = zipfile.ZipInfo(name, date_time=ARCHIVE_EPOCH)
    info.compress_type = compress
    # Without this the entry has mode 0, and some tools unpack it unreadable.
    info.external_attr = 0o644 << 16
    return info

# --------------------------------------------------------------------------
# EPUB
# --------------------------------------------------------------------------


def _xml(text: str) -> str:
    """Escape for XML text and attribute values.

    The titles here carry `#`, brackets and CJK, none of which need escaping —
    but `&` and `<` do, and an OPF that a reader refuses to parse is an EPUB
    with no metadata at all rather than a build failure. Cheaper to escape
    than to rely on nobody ever naming a fixture "Cloak & Dagger".
    """
    return (text.replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace('"', "&quot;"))


# The one-chapter body every fixture had before long books existed. Kept as
# the default so a book that is not *about* its length reads the same as it
# always did.
def _default_chapters(title: str, author: str) -> list[tuple[str, list[str]]]:
    return [(title, [f"By {author}.",
                     "Generated by stdjflib as library test content."])]


def write_epub(path: str, title: str, author: str,
               chapters: list[tuple[str, list[str]]] | None = None,
               cover: bytes | None = None) -> None:
    """A valid EPUB 3: mimetype, container, an OPF, a nav document, chapters.

    `chapters` is `[(chapter title, [paragraph, ...])]`; the default is the
    single short chapter these fixtures carried before long books existed.

    **The nav document and `dcterms:modified` are not decoration — EPUB 3
    requires both**, and every EPUB this tool wrote before them was invalid.
    A manifest item carrying `properties="nav"` is mandatory (EPUB 3.3 §5.1,
    "the EPUB navigation document"), as is a `<meta property="dcterms:modified">`
    in the package metadata (§3.4.3, the last-modified date is the one
    required `meta`). Neither is enforced by Jellyfin — `EpubProvider` reads
    `dc:title` out of the OPF and stops, so an invalid file resolved and
    displayed perfectly well. What could not be tested was the client: with
    one spine item and no TOC there is nothing for a reader to paginate
    through, no chapter to jump to and no table of contents to draw, so three
    of the four things an ebook reader does had no fixture at all.

    The nav document is deliberately **not** in the spine. EPUB 3 allows
    either, and leaving it out means the spine length is the chapter count
    exactly, which is what `epub_structure` reports and `verify` checks.

    `cover` is JPEG bytes. The OPF 3 spelling is a manifest item carrying
    `properties="cover-image"`, which is the *first* branch of
    `OpfReader.ReadCoverPath`; `write_epub2` carries the OPF 2 spelling, which
    is the last. Nothing draws artwork beside a book, so what the OPF declares
    is the only image the item can ever have.
    """
    chapters = chapters or _default_chapters(title, author)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    names = [f"ch{n}.xhtml" for n in range(1, len(chapters) + 1)]

    with zipfile.ZipFile(path, "w") as zf:
        # mimetype must be first and stored uncompressed — that is what makes
        # the file identifiable as an EPUB by its first bytes.
        zf.writestr(_member("mimetype", zipfile.ZIP_STORED),
                    "application/epub+zip")
        zf.writestr(_member("META-INF/container.xml"),
                    '<?xml version="1.0"?>\n'
                    '<container version="1.0" '
                    'xmlns="urn:oasis:names:tc:opendocument:xmlns:container">\n'
                    '  <rootfiles><rootfile full-path="OEBPS/content.opf" '
                    'media-type="application/oebps-package+xml"/></rootfiles>\n'
                    '</container>\n')

        manifest = ['    <item id="nav" href="nav.xhtml" '
                    'media-type="application/xhtml+xml" properties="nav"/>']
        if cover is not None:
            manifest.append('    <item id="cover-image" href="cover.jpg" '
                            'media-type="image/jpeg" '
                            'properties="cover-image"/>')
        spine = []
        for i, name in enumerate(names, 1):
            manifest.append(f'    <item id="c{i}" href="{name}" '
                            f'media-type="application/xhtml+xml"/>')
            spine.append(f'    <itemref idref="c{i}"/>')

        zf.writestr(_member("OEBPS/content.opf"),
                    f'<?xml version="1.0" encoding="utf-8"?>\n'
                    f'<package xmlns="http://www.idpf.org/2007/opf" version="3.0" '
                    f'unique-identifier="bookid">\n'
                    f'  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">\n'
                    f'    <dc:identifier id="bookid">stdjflib-{_xml(title)}</dc:identifier>\n'
                    f'    <dc:title>{_xml(title)}</dc:title>\n'
                    f'    <dc:creator>{_xml(author)}</dc:creator>\n'
                    f'    <dc:language>en</dc:language>\n'
                    # Required by EPUB 3, and `config.EPOCH` rather than the
                    # clock for the same reason every other date here is: two
                    # builds of one library must produce identical bytes.
                    f'    <meta property="dcterms:modified">{config.EPOCH}</meta>\n'
                    f'  </metadata>\n'
                    f'  <manifest>\n' + "\n".join(manifest) + f'\n  </manifest>\n'
                    f'  <spine>\n' + "\n".join(spine) + f'\n  </spine>\n'
                    f'</package>\n')

        toc = "\n".join(
            f'        <li><a href="{name}">{_xml(chapter)}</a></li>'
            for name, (chapter, _body) in zip(names, chapters))
        zf.writestr(_member("OEBPS/nav.xhtml"),
                    f'<?xml version="1.0" encoding="utf-8"?>\n'
                    f'<html xmlns="http://www.w3.org/1999/xhtml" '
                    f'xmlns:epub="http://www.idpf.org/2007/ops" lang="en">\n'
                    f'<head><title>{_xml(title)}</title></head><body>\n'
                    f'  <nav epub:type="toc" id="toc">\n'
                    f'    <h1>Contents</h1>\n'
                    f'    <ol>\n' + toc + f'\n    </ol>\n'
                    f'  </nav>\n'
                    f'</body></html>\n')

        if cover is not None:
            zf.writestr(_member("OEBPS/cover.jpg", zipfile.ZIP_STORED), cover)

        for name, (chapter, body) in zip(names, chapters):
            paras = "\n".join(f'<p>{_xml(p)}</p>' for p in body)
            zf.writestr(_member(f"OEBPS/{name}"),
                        f'<?xml version="1.0" encoding="utf-8"?>\n'
                        f'<html xmlns="http://www.w3.org/1999/xhtml" lang="en">'
                        f'<head>'
                        f'<title>{_xml(chapter)}</title></head><body>\n'
                        f'<h1>{_xml(chapter)}</h1>\n{paras}\n'
                        f'</body></html>\n')


# --------------------------------------------------------------------------
# EPUB 2
# --------------------------------------------------------------------------
#
# `OpfReader` never looks at the package `version` — it is a bag of XPaths,
# and roughly two thirds of them are **OPF 2 spellings an EPUB 3 file cannot
# satisfy**. Read out of
# `MediaBrowser.Providers/Books/OpenPackagingFormat/OpfReader.cs`:
#
# | What the server sets | Where it reads it from |
# | --- | --- |
# | `SeriesName` | `<meta name="calibre:series">` — OPF 2 only |
# | `IndexNumber` | `<meta name="calibre:series_index">` — OPF 2 only |
# | `CommunityRating` | `<meta name="calibre:rating">` — OPF 2 only |
# | `ForcedSortName` | OPF 3 `file-as`/`refines`, **or** `calibre:title_sort` |
# | ISBN / Amazon / GoogleBooks ids | `dc:identifier[@opf:scheme=...]` — OPF 2 only |
# | Primary image | OPF 3 `properties="cover-image"`, **or** `<meta name="cover">` |
# | people and their roles | `opf:role` on `dc:creator` — the OPF 2 attribute |
#
# So an all-EPUB-3 shelf reaches `dc:title`, `dc:creator` and `dc:language`
# and nothing else in that file. That is what this writer is for.
#
# The other half is the client: jellyfin-web pins `epubjs 0.3.93` and its
# table of contents calls `rendition.book.navigation`, which resolves the nav
# document for EPUB 3 and the **NCX** for EPUB 2 — two separate parsers, and
# the NCX one had no fixture.

# The NCX doctype. EPUB 2 requires it and epubcheck says so; it is also the
# one place here a DTD is named, which is why it is spelled out rather than
# assembled.
_NCX_DOCTYPE = ('<!DOCTYPE ncx PUBLIC "-//NISO//DTD ncx 2005-1//EN" '
                '"http://www.daisy.org/z3986/2005/ncx-2005-1.dtd">')

_XHTML11_DOCTYPE = ('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" '
                    '"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">')


def write_epub2(path: str, title: str, author: str, *,
                chapters: list[tuple[str, list[str]]] | None = None,
                identifier: str = "",
                scheme_ids: tuple[tuple[str, str], ...] = (),
                series: str = "", series_index: int | None = None,
                sort_title: str = "", rating: int | None = None,
                description: str = "", publisher: str = "",
                subjects: tuple[str, ...] = (), date: str = "",
                creators: tuple[tuple[str, str], ...] = (),
                cover: bytes | None = None) -> None:
    """An EPUB 2.0.1: an OPF 2 package, an NCX table of contents, chapters.

    Everything after `chapters` is a field `OpfReader` reads and that an
    EPUB 3 file has no way to express. `creators` is `(role, name)` where role
    is a MARC relator code — `aut`, `edt`, `ill`, `nrt`, `art`, `arr`, `lyr`,
    `mus` — which the server maps onto `PersonKind`; `author` is used when
    `creators` is empty.

    `cover` is JPEG bytes. The OPF 2 spelling is a `<meta name="cover">`
    naming a manifest item id, and the server's own lookup for it is odd
    enough to be worth stating: it first tries `Path.Combine("Images",
    content)` as an *href*, which no ordinary EPUB matches, and only then
    looks the id up directly. The second branch is the one that works.
    """
    chapters = chapters or _default_chapters(title, author)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    names = [f"ch{n}.xhtml" for n in range(1, len(chapters) + 1)]
    uid = identifier or f"stdjflib-{title}"

    meta = [f'    <dc:identifier id="bookid">{_xml(uid)}</dc:identifier>']
    for scheme, value in scheme_ids:
        meta.append(f'    <dc:identifier opf:scheme="{_xml(scheme)}">'
                    f'{_xml(value)}</dc:identifier>')
    meta.append(f'    <dc:title>{_xml(title)}</dc:title>')
    meta.append('    <dc:language>en</dc:language>')
    for role, name in (creators or (("aut", author),)):
        meta.append(f'    <dc:creator opf:role="{_xml(role)}">'
                    f'{_xml(name)}</dc:creator>')
    if description:
        meta.append(f'    <dc:description>{_xml(description)}</dc:description>')
    if publisher:
        meta.append(f'    <dc:publisher>{_xml(publisher)}</dc:publisher>')
    for subject in subjects:
        meta.append(f'    <dc:subject>{_xml(subject)}</dc:subject>')
    if date:
        meta.append(f'    <dc:date>{_xml(date)}</dc:date>')
    # The `name`/`content` form. This is what makes these fields reachable at
    # all — there is no OPF 3 spelling of `calibre:series` in `OpfReader`.
    if series:
        meta.append(f'    <meta name="calibre:series" content="{_xml(series)}"/>')
    if series_index is not None:
        meta.append(f'    <meta name="calibre:series_index" '
                    f'content="{series_index}"/>')
    if sort_title:
        meta.append(f'    <meta name="calibre:title_sort" '
                    f'content="{_xml(sort_title)}"/>')
    if rating is not None:
        meta.append(f'    <meta name="calibre:rating" content="{rating}"/>')
    if cover is not None:
        meta.append('    <meta name="cover" content="cover-image"/>')

    manifest = ['    <item id="ncx" href="toc.ncx" '
                'media-type="application/x-dtbncx+xml"/>']
    if cover is not None:
        manifest.append('    <item id="cover-image" href="cover.jpg" '
                        'media-type="image/jpeg"/>')
    spine = []
    for i, name in enumerate(names, 1):
        manifest.append(f'    <item id="c{i}" href="{name}" '
                        f'media-type="application/xhtml+xml"/>')
        spine.append(f'    <itemref idref="c{i}"/>')

    nav_points = "\n".join(
        f'    <navPoint id="np{i}" playOrder="{i}">\n'
        f'      <navLabel><text>{_xml(chapter)}</text></navLabel>\n'
        f'      <content src="{name}"/>\n'
        f'    </navPoint>'
        for i, (name, (chapter, _body)) in enumerate(zip(names, chapters), 1))

    with zipfile.ZipFile(path, "w") as zf:
        zf.writestr(_member("mimetype", zipfile.ZIP_STORED),
                    "application/epub+zip")
        zf.writestr(_member("META-INF/container.xml"),
                    '<?xml version="1.0"?>\n'
                    '<container version="1.0" '
                    'xmlns="urn:oasis:names:tc:opendocument:xmlns:container">\n'
                    '  <rootfiles><rootfile full-path="OEBPS/content.opf" '
                    'media-type="application/oebps-package+xml"/></rootfiles>\n'
                    '</container>\n')
        zf.writestr(_member("OEBPS/content.opf"),
                    f'<?xml version="1.0" encoding="utf-8"?>\n'
                    f'<package xmlns="http://www.idpf.org/2007/opf" '
                    f'version="2.0" unique-identifier="bookid">\n'
                    # Both prefixes are declared here: `opf:scheme` and
                    # `opf:role` are read by *prefixed name*, so an OPF that
                    # only sets the default namespace cannot express them.
                    f'  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/" '
                    f'xmlns:opf="http://www.idpf.org/2007/opf">\n'
                    + "\n".join(meta) +
                    f'\n  </metadata>\n'
                    f'  <manifest>\n' + "\n".join(manifest) +
                    f'\n  </manifest>\n'
                    # `toc="ncx"` is what points the spine at the NCX. Without
                    # it the file is invalid and a reader has no contents.
                    f'  <spine toc="ncx">\n' + "\n".join(spine) +
                    f'\n  </spine>\n'
                    f'</package>\n')
        zf.writestr(_member("OEBPS/toc.ncx"),
                    f'<?xml version="1.0" encoding="utf-8"?>\n'
                    f'{_NCX_DOCTYPE}\n'
                    f'<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" '
                    f'version="2005-1">\n'
                    f'  <head>\n'
                    f'    <meta name="dtb:uid" content="{_xml(uid)}"/>\n'
                    f'    <meta name="dtb:depth" content="1"/>\n'
                    f'    <meta name="dtb:totalPageCount" content="0"/>\n'
                    f'    <meta name="dtb:maxPageNumber" content="0"/>\n'
                    f'  </head>\n'
                    f'  <docTitle><text>{_xml(title)}</text></docTitle>\n'
                    f'  <navMap>\n' + nav_points + f'\n  </navMap>\n'
                    f'</ncx>\n')
        if cover is not None:
            zf.writestr(_member("OEBPS/cover.jpg", zipfile.ZIP_STORED), cover)
        for name, (chapter, body) in zip(names, chapters):
            paras = "\n".join(f'<p>{_xml(p)}</p>' for p in body)
            zf.writestr(_member(f"OEBPS/{name}"),
                        f'<?xml version="1.0" encoding="utf-8"?>\n'
                        f'{_XHTML11_DOCTYPE}\n'
                        f'<html xmlns="http://www.w3.org/1999/xhtml">'
                        f'<head><title>{_xml(chapter)}</title></head><body>\n'
                        f'<h1>{_xml(chapter)}</h1>\n{paras}\n'
                        f'</body></html>\n')


def epub_structure(path: str) -> dict | None:
    """Read an EPUB back for `verify`: version, title, spine, contents, cover.

    Deliberately a second statement of the format rather than a call back into
    the writers, for the same reason `verify._ARTWORK_STEMS` restates the
    artwork mapping and `strm.first_line` restates the `.strm` rule: a check
    that inherits its expectations from the thing it checks is not a check.

    The OPF is located through `META-INF/container.xml` rather than assumed at
    `OEBPS/content.opf`, which is what `EpubUtils.ReadContentFilePath` does.

    `cover` restates `OpfReader.ReadCoverPath` — the OPF 3 `cover-image`
    property, then the OPF 2 `<meta name="cover">` naming a manifest id. The
    server has two further branches between them and **neither can ever
    match**: `//opf:item[@id='cover' and @media-type='image/*']` and
    `//opf:item[@id='*cover-image']` are XPath *string literals*, not globs,
    and an `id` of `*cover-image` is not even a well-formed NCName. Read from
    source, not measured against a server; they are left out here because a
    fixture cannot reach them.
    """
    import posixpath
    import xml.etree.ElementTree as ET

    OPF = "{http://www.idpf.org/2007/opf}"
    DC = "{http://purl.org/dc/elements/1.1/}"
    CONTAINER = "{urn:oasis:names:tc:opendocument:xmlns:container}"
    try:
        with zipfile.ZipFile(path) as zf:
            container = ET.fromstring(zf.read("META-INF/container.xml"))
            root = container.find(f".//{CONTAINER}rootfile")
            if root is None or not root.get("full-path"):
                return None
            opf_path = root.get("full-path")
            opf = ET.fromstring(zf.read(opf_path))
            names = set(zf.namelist())
    except (OSError, KeyError, zipfile.BadZipFile, ET.ParseError):
        return None

    base = posixpath.dirname(opf_path)

    def resolved(href: str | None) -> str | None:
        """A manifest href is relative to the OPF, not to the archive root."""
        if not href:
            return None
        full = posixpath.normpath(posixpath.join(base, href)) if base else href
        return full if full in names else None

    manifest = opf.find(f"{OPF}manifest")
    spine = opf.find(f"{OPF}spine")
    if manifest is None or spine is None:
        return None
    items = manifest.findall(f"{OPF}item")
    by_id = {item.get("id"): item for item in items}

    nav = [item for item in items
           if "nav" in (item.get("properties") or "").split()]
    # EPUB 2's contents are an NCX, pointed at by the spine's `toc` attribute.
    ncx = by_id.get(spine.get("toc") or "")

    cover = None
    prop = [item for item in items
            if "cover-image" in (item.get("properties") or "").split()]
    if prop:
        cover = resolved(prop[0].get("href"))
    else:
        meta_cover = [m for m in opf.findall(f"{OPF}metadata/{OPF}meta")
                      if m.get("name") == "cover"]
        if meta_cover:
            item = by_id.get(meta_cover[0].get("content") or "")
            cover = resolved(item.get("href")) if item is not None else None

    title = opf.find(f"{OPF}metadata/{DC}title")
    modified = [m for m in opf.findall(f"{OPF}metadata/{OPF}meta")
                if m.get("property") == "dcterms:modified"]
    return {
        "version": opf.get("version"),
        "title": None if title is None else title.text,
        "spine": len(spine.findall(f"{OPF}itemref")),
        # Declared *and* present in both cases: a manifest entry pointing at
        # nothing is the failure this is most likely to be asked about.
        "nav": bool(nav) and bool(resolved(nav[0].get("href"))),
        "ncx": ncx is not None and bool(resolved(ncx.get("href"))),
        "modified": modified[0].text if modified else None,
        "cover": cover,
    }


# --------------------------------------------------------------------------
# Body text
# --------------------------------------------------------------------------
#
# A book with two sentences in it cannot be paginated, and pagination is most
# of what an ebook reader does. The long fixtures therefore carry real volume,
# and it has to be *derived* rather than random: two builds of the same
# library must produce identical bytes, and `random` seeded from the clock and
# `hash()` both fail that — Python salts string hashing per process, so
# `hash()` looks deterministic within one run and is not.
#
# Lorem rather than English prose because the text is never read: what is
# under test is how much of it there is and how it flows into columns. The
# non-Latin chapters come from `subs.SCRIPTS`, which already holds real
# sentences per script for exactly this reason, and they are composed in
# `libraries.py` rather than here — this module writes formats, it does not
# decide what a fixture says.

_LOREM_WORDS = (
    "lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod "
    "tempor incididunt ut labore et dolore magna aliqua enim ad minim veniam "
    "quis nostrud exercitation ullamco laboris nisi aliquip ex ea commodo "
    "consequat duis aute irure in reprehenderit voluptate velit esse cillum "
    "eu fugiat nulla pariatur excepteur sint occaecat cupidatat non proident "
    "sunt culpa qui officia deserunt mollit anim id est laborum"
).split()


def _derived_bytes(key: str):
    """An endless byte stream derived from `key`, and from nothing else."""
    counter = 0
    while True:
        yield from hashlib.sha256(f"{key}:{counter}".encode("utf-8")).digest()
        counter += 1


def paragraphs(key: str, count: int, *, sentences: tuple[int, int] = (4, 9),
               words: tuple[int, int] = (7, 17)) -> list[str]:
    """`count` paragraphs of filler, the same every time for the same `key`."""
    src = _derived_bytes(key)

    def pick(lo: int, hi: int) -> int:
        return lo + next(src) % (hi - lo + 1)

    out = []
    for _ in range(count):
        body = []
        for _ in range(pick(*sentences)):
            n = pick(*words)
            chosen = [_LOREM_WORDS[next(src) % len(_LOREM_WORDS)]
                      for _ in range(n)]
            # A comma in the longer sentences, so a line-breaking bug has
            # something other than spaces to break at.
            if n > 10:
                chosen[pick(3, n - 3)] += ","
            body.append(" ".join([chosen[0].capitalize()] + chosen[1:]) + ".")
        out.append(" ".join(body))
    return out


# --------------------------------------------------------------------------
# PDF
# --------------------------------------------------------------------------
#
# Written by hand rather than with a library, and it is a smaller job than it
# sounds: a PDF is a list of numbered objects, a cross-reference table of their
# byte offsets, and a trailer naming the catalogue. The only part that has to
# be exactly right is the xref — every entry is a ten-digit offset in a
# twenty-byte record, and a reader that cannot parse it falls back to scanning
# the file and finds the pages anyway, which is how a broken one still opens.
# So the offsets are measured from the bytes actually emitted, never computed
# ahead of them.
#
# The page count is the whole point of the fixture: Jellyfin stores it as
# `RunTimeTicks`, so it is the one number a client can read back off a book.


def _pdf_escape(text: str) -> str:
    """Escape for a PDF literal string. Backslash first or it doubles."""
    return text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")


def _pdf_ascii(text: str) -> bytes:
    """PDF literal strings here are WinAnsi; anything else becomes '?'.

    The fixture titles are Latin on purpose, so this only ever bites if
    someone gives a PDF a Japanese name — at which point a replaced character
    in a page of body text is a better outcome than a build that fails.
    """
    return _pdf_escape(text).encode("ascii", "replace")


def _wrap_ascii(text: str, width: int) -> list[str]:
    """Greedy wrap. Helvetica at 11pt averages about half its size per glyph,
    so 78 columns is a little under the 468pt of usable width."""
    lines, line = [], ""
    for word in text.split():
        if line and len(line) + 1 + len(word) > width:
            lines.append(line)
            line = word
        else:
            line = f"{line} {word}" if line else word
    if line:
        lines.append(line)
    return lines


# How much filler a body page holds, and where it starts. The four header
# lines are 22pt on 32pt leading from y=700, so the last of them sits at 604 —
# a body block starting at 600 overlaps its descenders, and `pdftotext` reads
# the two interleaved word by word. Measured, not guessed. Starting at 560
# clears it; 30 lines at 16pt then runs down to y=96, above the bottom margin.
_PDF_BODY_TOP = 560
_PDF_BODY_LINES = 30
_PDF_BODY_COLUMNS = 78


def pdf_bytes(title: str, author: str, pages: int,
              body_key: str | None = None) -> bytes:
    """A valid multi-page PDF, with `pages` pages of readable text.

    With `body_key`, every page also carries a screenful of derived filler, so
    a long PDF is a document rather than a stack of headers. Off by default:
    the short fixtures exist to be counted, and giving them body text would
    change files whose only job is their page count.
    """
    if pages < 1:
        raise ValueError("a PDF needs at least one page")
    bodies: list[bytes] = []

    def add(body: bytes) -> int:
        bodies.append(body)
        return len(bodies)

    catalog = add(b"")        # 1 — patched below, once the pages exist
    pages_node = add(b"")     # 2 — likewise; every page names it as /Parent
    font = add(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica "
               b"/Encoding /WinAnsiEncoding >>")

    kids = []
    for n in range(1, pages + 1):
        lines = [title, f"By {author}.", f"Page {n} of {pages}.",
                 "Generated by stdjflib as library test content."]
        data = (b"BT /F1 22 Tf 72 700 Td 32 TL\n"
                + b"".join(b"(%s) Tj T*\n" % _pdf_ascii(line)
                           for line in lines)
                + b"ET\n")
        if body_key is not None:
            # Keyed per page, so no two pages of a long book are the same
            # screenful — a reader that redraws the wrong page is then visible
            # rather than plausible.
            filler = " ".join(paragraphs(f"{body_key}:page{n}", 3))
            wrapped = _wrap_ascii(filler, _PDF_BODY_COLUMNS)[:_PDF_BODY_LINES]
            data += (b"BT /F1 11 Tf 72 %d Td 16 TL\n" % _PDF_BODY_TOP
                     + b"".join(b"(%s) Tj T*\n" % _pdf_ascii(line)
                                for line in wrapped)
                     + b"ET\n")
        content = add(b"<< /Length %d >>\nstream\n" % len(data)
                      + data + b"endstream")
        kids.append(add(
            b"<< /Type /Page /Parent %d 0 R /MediaBox [0 0 612 792] "
            b"/Resources << /Font << /F1 %d 0 R >> >> /Contents %d 0 R >>"
            % (pages_node, font, content)))

    bodies[catalog - 1] = b"<< /Type /Catalog /Pages %d 0 R >>" % pages_node
    bodies[pages_node - 1] = (
        b"<< /Type /Pages /Count %d /Kids [%s] >>"
        % (pages, b" ".join(b"%d 0 R" % k for k in kids)))

    # The binary comment on line two is what tells a transfer agent this is not
    # a text file. Dropping it is legal and gets the file mangled by anything
    # that thinks it may translate line endings.
    out = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = []
    for number, body in enumerate(bodies, 1):
        offsets.append(len(out))
        out += b"%d 0 obj\n" % number + body + b"\nendobj\n"

    xref = len(out)
    out += b"xref\n0 %d\n" % (len(bodies) + 1)
    # Object zero is always the head of the free list, and the records are
    # fixed-width: exactly twenty bytes each, trailing space included.
    out += b"0000000000 65535 f \n"
    for offset in offsets:
        out += b"%010d 00000 n \n" % offset
    out += (b"trailer\n<< /Size %d /Root %d 0 R /Info << /Title (%s) "
            b"/Author (%s) >> >>\n"
            % (len(bodies) + 1, catalog, _pdf_ascii(title), _pdf_ascii(author)))
    out += b"startxref\n%d\n%%%%EOF\n" % xref
    return bytes(out)


def write_pdf(path: str, title: str, author: str, pages: int,
              body_key: str | None = None) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as fh:
        fh.write(pdf_bytes(title, author, pages, body_key))


def pdf_page_count(path: str) -> int | None:
    """Count a PDF's pages by reading the file, for `verify`.

    Deliberately a second statement of the format rather than a call back into
    the writer — a check that inherits its expectations from the thing it is
    checking is not a check, which is the same reason `verify._ARTWORK_STEMS`
    spells the artwork mapping out again. This counts page *objects*, where
    the writer declares a `/Count`, so the two disagree if either is wrong.
    """
    try:
        with open(path, "rb") as fh:
            blob = fh.read()
    except OSError:
        return None
    if not blob.startswith(b"%PDF-"):
        return None
    # `/Type /Pages` is the tree node and `/Type /Page` a leaf; matching the
    # shorter one first would count the node as a page. Both spellings of the
    # separator occur in the wild.
    count = 0
    for token in (b"/Type/Page", b"/Type /Page"):
        start = 0
        while True:
            at = blob.find(token, start)
            if at < 0:
                break
            start = at + len(token)
            tail = blob[start:start + 1]
            # A leaf ends here; `/Pages` continues with an "s".
            if tail in (b"", b" ", b"/", b">", b"\r", b"\n", b"\t"):
                count += 1
    return count


# --------------------------------------------------------------------------
# Comic archives
# --------------------------------------------------------------------------


def write_cbz(path: str, pages: list[tuple[str, str]], *,
              comment: bytes | None = None,
              extra: dict[str, str] | None = None) -> None:
    """A comic archive: a zip of images, which is all a CBZ is.

    `pages` is (name-in-archive, path-on-disk); `extra` adds text members such
    as an internal `ComicInfo.xml`; `comment` is the zip's *archive* comment,
    which is where the ComicBookInfo dialect lives.

    Stored rather than deflated, matching what comic archives are in the wild —
    the pages are JPEG and already compressed, so deflating them buys nothing
    and costs a scan every time something opens the file.
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with zipfile.ZipFile(path, "w", zipfile.ZIP_STORED) as zf:
        for name, source in pages:
            # Not `zf.write(source, name)`: that takes the entry's timestamp
            # from the file on disk, so the archive would differ between two
            # builds of an identical library.
            with open(source, "rb") as fh:
                zf.writestr(_member(name, zipfile.ZIP_STORED), fh.read())
        for name, text in (extra or {}).items():
            zf.writestr(_member(name, zipfile.ZIP_STORED), text)
        if comment is not None:
            zf.comment = comment


def write_cbt(path: str, pages: list[tuple[str, str]], *,
              extra: dict[str, str] | None = None) -> None:
    """A comic archive as a tar, which is what `.cbt` is.

    Jellyfin reads `.cb7`, `.cbr`, `.cbt` and `.cbz` through SharpCompress, so
    a tar gets a cover and a page count exactly as a zip does — but the two
    metadata providers that read *inside* an archive are hard-restricted to
    `.cbz`, so the `ComicInfo.xml` this puts in is deliberately never read.
    That is the fixture: the same bytes in a `.cbz` are metadata and here are
    a page.

    `.cbt` rather than `.cbr` because a RAR cannot be written from the
    standard library and this can. It answers the same question.
    """
    import io
    import tarfile

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with tarfile.open(path, "w") as tf:
        for name, source in pages:
            info = tarfile.TarInfo(name)
            info.size = os.path.getsize(source)
            # Not the file's mtime: a tar records it, so the archive would
            # differ between two builds of the same library.
            info.mtime = 0
            info.mode = 0o644
            info.uid = info.gid = 0
            info.uname = info.gname = ""
            with open(source, "rb") as fh:
                tf.addfile(info, fh)
        for name, text in (extra or {}).items():
            data = text.encode("utf-8")
            info = tarfile.TarInfo(name)
            info.size = len(data)
            info.mtime = 0
            info.mode = 0o644
            info.uid = info.gid = 0
            info.uname = info.gname = ""
            tf.addfile(info, io.BytesIO(data))


def comicinfo_xml(*, title: str, series: str, number: int, year: int,
                  summary: str, publisher: str, genres: list[str],
                  writer: str, penciller: str = "", colourist: str = "",
                  language: str = "en") -> str:
    """The ComicRack `ComicInfo.xml` dialect, as `ComicInfoReader` reads it.

    Only the elements the server has an XPath for are written. It reads
    Title, Series, Number, Summary, Year/Month/Day, Genre (comma split),
    Publisher, LanguageISO and Manga, plus the people — and `Colourist` is
    spelled the British way in the server, which is the kind of detail a
    fixture exists to pin.
    """
    def esc(text: str) -> str:
        return (str(text).replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;"))

    rows = [
        ("Title", title), ("Series", series), ("Number", number),
        ("Summary", summary), ("Year", year), ("Month", 1), ("Day", 1),
        ("Genre", ", ".join(genres)), ("Publisher", publisher),
        ("Writer", writer), ("Penciller", penciller),
        ("Colourist", colourist), ("LanguageISO", language),
    ]
    body = "".join(f"  <{tag}>{esc(value)}</{tag}>\n"
                   for tag, value in rows if value != "")
    return ('<?xml version="1.0" encoding="utf-8"?>\n'
            '<ComicInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
            'xmlns:xsd="http://www.w3.org/2001/XMLSchema">\n'
            f'{body}</ComicInfo>\n')


def comicbookinfo_json(*, title: str, series: str, issue: int, year: int,
                       month: int, publisher: str, genre: str, comments: str,
                       credits: list[tuple[str, str]], tags: list[str],
                       language: str = "en") -> bytes:
    """The ComicBookInfo dialect, which lives in the zip's *archive comment*.

    A zip comment is a free-text trailer nothing else looks at, which is why
    this convention could be bolted onto an existing format at all — and why
    it is invisible to anything that only lists entries. The server reads it
    with `JsonSerializer` into `ComicBookInfoFormat`, so the container key has
    to be spelled exactly `ComicBookInfo/1.0`.

    `credits` is (person, role); the role is parsed with
    `Enum.TryParse<PersonKind>`, so an unrecognised one silently becomes
    `Unknown` rather than failing.
    """
    payload = {
        "appID": "stdjflib/1.0",
        # Not "now": a wall-clock stamp here would make two builds of the same
        # library differ, which is the one thing this tool must never do.
        "lastModified": "2020-01-01 00:00:00 +0000",
        "ComicBookInfo/1.0": {
            "series": series,
            "title": title,
            "issue": issue,
            "publisher": publisher,
            "publicationMonth": month,
            "publicationYear": year,
            "genre": genre,
            "language": language,
            "comments": comments,
            "credits": [{"person": person, "role": role}
                        for person, role in credits],
            "tags": tags,
        },
    }
    return json.dumps(payload, ensure_ascii=False,
                      separators=(",", ":")).encode("utf-8")


# --------------------------------------------------------------------------
# The formats that resolve and cannot be opened
# --------------------------------------------------------------------------

def palmdb_bytes(title: str, creator: str) -> bytes:
    """A PalmDB header, which is what a `.mobi` and an `.azw3` both are.

    Deliberately a header and nothing else: the point of these fixtures is
    that Jellyfin *catalogues* them — `BookResolver` accepts the extension and
    hands back an ordinary Book with metadata and artwork — while no client
    can open one. Nothing in the server parses a byte of the content, so a
    real book inside would test nothing that this does not.

    It is a genuine PalmDB header rather than arbitrary bytes so that the file
    is at least structurally what its extension claims. Anything that tries to
    read further will find no records and should say so, which is the honest
    outcome for a file that exists to have no reader.
    """
    name = title.encode("ascii", "replace")[:31].ljust(32, b"\x00")
    header = bytearray(name)
    header += (0).to_bytes(2, "big")     # attributes
    header += (0).to_bytes(2, "big")     # version
    # PalmDB times are seconds since 1904. Fixed, not "now" — see EPOCH.
    stamp = (2020 - 1904) * 365 * 24 * 3600
    header += stamp.to_bytes(4, "big")   # creation date
    header += stamp.to_bytes(4, "big")   # modification date
    header += (0).to_bytes(4, "big")     # last backup
    header += (0).to_bytes(4, "big")     # modification number
    header += (0).to_bytes(4, "big")     # app info id
    header += (0).to_bytes(4, "big")     # sort info id
    header += b"BOOK"                    # type
    header += b"MOBI"                    # creator
    header += (0).to_bytes(4, "big")     # unique id seed
    header += (0).to_bytes(4, "big")     # next record list id
    header += (0).to_bytes(2, "big")     # number of records
    trailer = (f"stdjflib placeholder. {title}, by {creator}. "
               f"This file has a valid PalmDB header and no book inside: "
               f"Jellyfin catalogues it and no client can open it, which is "
               f"the case it exists to cover.\n").encode("utf-8")
    return bytes(header) + trailer


def write_palmdb(path: str, title: str, creator: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as fh:
        fh.write(palmdb_bytes(title, creator))


# --------------------------------------------------------------------------
# Reading back, for `verify`
# --------------------------------------------------------------------------

# What `ComicImageProvider` will open, and what it will accept as a page.
ARCHIVE_EXTENSIONS = (".cb7", ".cbr", ".cbt", ".cbz")
COVER_EXTENSIONS = (".png", ".jpeg", ".jpg", ".webp", ".bmp", ".gif")


def archive_entries(path: str) -> list[str] | None:
    """Every non-directory entry in a comic archive, or None if unreadable.

    The count matters because it *is* the page count: `ProbeProvider` stores
    `archive.Entries.Count(e => !e.IsDirectory) * 10000` as `RunTimeTicks`,
    counting a `ComicInfo.xml` as cheerfully as a page.
    """
    import tarfile

    try:
        if path.lower().endswith(".cbz"):
            with zipfile.ZipFile(path) as zf:
                return [i.filename for i in zf.infolist() if not i.is_dir()]
        if path.lower().endswith(".cbt"):
            with tarfile.open(path) as tf:
                return [m.name for m in tf.getmembers() if not m.isdir()]
    except (OSError, zipfile.BadZipFile, tarfile.TarError):
        return None
    return None


def archive_cover(names: list[str]) -> str | None:
    """Which entry Jellyfin would use as the cover.

    `ComicImageProvider.FindCoverEntryInArchiveAsync`, restated rather than
    called: an entry named exactly `cover.<ext>` — tried in the order below,
    which puts `.png` ahead of `.jpg` — and otherwise the alphabetically first
    entry by full key that has an image extension. Both halves matter: the
    exact match takes no path prefix and is case-sensitive, so `Cover.jpg` and
    `images/cover.jpg` both fall through to the sort.
    """
    for ext in COVER_EXTENSIONS:
        if "cover" + ext in names:
            return "cover" + ext
    for name in sorted(names):
        if os.path.splitext(name)[1].lower() in COVER_EXTENSIONS:
            return name
    return None
